on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/cevin/rpmbuild:rhel9
    steps:
    - uses: actions/checkout@v3

    - name: build RPM package
      run: |
          rpmbuild -ba SPECS/openssl.spec 

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary RPM
        path: ${{ steps.rpm.outputs.rpm_dir_apth }}

